### PR TITLE
Rechecking branch

### PR DESCRIPTION
**Pull request by mkayumov19**
New one

### CODE REVIEW

**Comment by halideimir** [comment]
looks clean

**Review by fburgazli — APPROVED** [review]
let s merge it
thanks for cleaning up

**Comment by AygunEldar** [comment]
It is commented

**Comment by halideimir** [comment]
I will approve it

**Comment by arteaby31** [comment]
I will aprove

**Review by halideimir — APPROVED** [review]
ok

**Review by AygunEldar — APPROVED** [review]
Again commented

**Review by arteaby31 — APPROVED** [review]
I aprove it

**Review by mariamrashad82 — APPROVED** [review]
approved

**Pull request merged**
